@startuml
allow_mixing
rectangle MobileApp {
  together {
    together {
      package Screens {
        rectangle Screen1 {
          component View1
          component Data1
          Data1 --> View1
          Models <-- Data1
        }
        rectangle Screen2 {
          component View2
          component Data2
          Data2 --> View2
          Models <-- Data2
        }
      }
      package Components {
        rectangle Component1 {
          component ComView1
          component ComData1
          ComData1 --> ComView1
        }
        rectangle Component2 {
          component ComView2
          component ComData2
          ComData2 --> ComView2
        }
      }
    }
    together {
      package Models {
        rectangle UserModel
        rectangle AdvisorModel
        rectangle TransactionModel
        rectangle ProfileModel
      }
      package Providers {
        rectangle AuthProvider
        rectangle I18nProvider
        rectangle OthersProviders
      }
    }
  }
  
  together {
    together {
      package UnitzLib {
        object gstyle {
          styleguides
          spacings
          colors
        }
        collections hooks
        collections utils
        collections translations
      }
      package "3rd party libraries" {
        collections Navigation
        collections Clients
      }
    }
    together {
      usecase Routes
      node "State Management/Apollo Clients" as StateMan
    }
  }

  together {
    rectangle Network
    rectangle LocalStorage
  }

  View1 ----> gstyle
  View2 ----> gstyle
  ComView1 ----> gstyle
  ComView2 ----> gstyle

  Routes --> Screens
  Routes --> Providers
  Models --> UnitzLib

  Models -do----> StateMan
  Screens -do----> StateMan
  Providers -do----> StateMan
  Components -do----> StateMan
}

StateMan ---> Network
StateMan ---> LocalStorage
cloud Internet

Network --> Internet
rectangle Services {
  rectangle "Firebase Auth"
  rectangle "Firebase Functions"
  rectangle "Hasura Data"
  rectangle "Contentful Advisor"
  rectangle "Contentful Article"
}

Internet -do-> Services

@enduml