# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase distribution"
  lane :stage do
    
    gradle(task: "assembleRelease")
    
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Update appicon"
  lane :update_appicon do
    android_appicon(
      appicon_image_file: '../../../modules/unitz-assets/Icon.png',
      appicon_path: 'app/src/main/res/mipmap',
      generate_rounded: true
    )
  end
  
  desc "Update splash"
  lane :update_splash do
    android_appicon(
      appicon_image_file: '../../../modules/unitz-assets/splash.png',
      appicon_icon_types: %i[splash_port splash_land],
      appicon_path: 'app/src/main/res_t/drawable/splash',
      appicon_filename: 'splash'
    )
  end
end
