name: FIB Distribution ios

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - "master"
    # tags:
    #   - "v*"
# defaults:
#   run:
#     working-directory: ./your_working_dir
jobs:
  dist-fib-ios:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    env:
      working-directory: ./ws/packages/unitz-mobile
    steps:
      - name: setup node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: clone workspace
        uses: actions/checkout@v2
        with:
          repository: Unitz-Co/ws-app-mobile
          path: ws
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: checkout submodule
        run: |
          cd ws
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.PAT_TOKEN }}:${{ secrets.PAT_TOKEN }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - name: build modules
        working-directory: ${{env.working-directory}}
        run: |
          yarn install
      - name: install pod
        working-directory: ${{env.working-directory}}
        run: |
          cd ios
          pod install
      - name: Create IPA Build
        working-directory: ${{env.working-directory}}
        env:
          # APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
          # DEVELOPER_TEAM_ID: ${{ secrets.DEVELOPER_TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: |
          cd ios
          fastlane beta

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: ${{env.working-directory}}/ios/builds/unitzmobile.ipa
